- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp
  tags:
    - config

- name: "Create document root for Virtual Host"
  file:
    path: "/var/www/{{ hostname }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'
  tags:
    - config

- name: Set up Apache Virtual Host
  template:
    src: "files/virtual-host.conf.j2"
    dest: "/etc/apache2/sites-available/{{ hostname }}.conf"
  notify: reload-apache
  tags:
    - config

- name: "enable rewrite module"
  shell: /usr/sbin/a2enmod rewrite
  notify: reload-apache
  tags:
    - config

- name: "enable new site"
  shell: /usr/sbin/a2ensite {{ hostname }}.conf
  notify: reload-apache
  tags:
    - config

- name: "disable default Apache website"
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: restart-apache
  tags:
    - config
