- name: write the apache config file
  notify: restart-apache
  template:
    src: templates/ports.conf.j2
    dest: /etc/apache2/ports.conf

- name: "UFW - Allow HTTP on port {{ http_port }}"
  ufw:
    rule: allow
    port: "{{ http_port }}"
    proto: tcp

- name: "Create document root for Virtual Host"
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0755'

- name: write the apache index page
  notify: restart-apache
  template:
    src: templates/index.conf.j2
    dest: /var/www/{{ http_host }}/index.html

- name: Set up Apache Virtual Host
  template:
    src: "files/virtual-host.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
  notify: reload-apache

- name: "enable rewrite module"
  shell: /usr/sbin/a2enmod rewrite
  notify: reload-apache

- name: "enable new virtual host"
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: reload-apache

- name: "disable default Apache website"
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: restart-apache

- name: "make sure your configuration file doesn't contain syntax errors"
  shell: /usr/sbin/apache2ctl configtest
  notify: restart-apache

- name: "ensure apache is running and changes effected"
  service:
    name: apache2
    state: started